server {
  listen 80;
  server_name aroche.local;

  root /var/www/main;
  index index.html;

  location ^~ /_shared/ {
    alias /var/www/_shared/;
  }

  location / {
    try_files $uri $uri/ =404;
  }
}

server {
  listen 443 ssl;
  server_name aroche.local;

  ssl_certificate     /etc/nginx/certs/secure/secure.crt;
  ssl_certificate_key /etc/nginx/certs/secure/secure.key;

  ssl_protocols TLSv1.2 TLSv1.3;
  ssl_prefer_server_ciphers on;
  ssl_ciphers 'TLS_AES_256_GCM_SHA384:TLS_AES_128_GCM_SHA256:TLS_CHACHA20_POLY1305_SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256';
  ssl_session_cache shared:SSL:10m;
  ssl_session_timeout 10m;

  root /var/www/main;
  index index.html;

  location ^~ /_shared/ {
    alias /var/www/_shared/;
  }

  location / {
    try_files $uri $uri/ =404;
  }
}

